import { describe, expect, it } from 'vitest'
import { stripAiTrailers } from './strip-ai-trailers.ts'

function withTrailer(trailer: string): string {
  return `fix: 修正\n\n正文\n\n${trailer}\n`
}

describe('stripAiTrailers', () => {
  it('去掉 Claude 的 Co-Authored-By 与 Claude Code 水印，保留正文', () => {
    const message = [
      'feat: 新增登录接口',
      '',
      '说明第一行',
      '',
      '🤖 Generated with [Claude Code](https://claude.com/claude-code)',
      '',
      'Co-Authored-By: Claude Opus 5.5 (1M context) <noreply@anthropic.com>',
      '',
    ].join('\n')
    expect(stripAiTrailers(message)).toBe('feat: 新增登录接口\n\n说明第一行\n')
  })

  it.each([
    'Co-authored-by: Claude <noreply@anthropic.com>',
    'Co-Authored-By : Claude <noreply@anthropic.com>',
    'Assisted-by: Claude <noreply@anthropic.com>',
    'Signed-off-by: Claude <noreply@anthropic.com>',
    'co-authored-by: GitHub Copilot <copilot@github.com>',
    'Co-authored-by: Copilot <175728472+Copilot@users.noreply.github.com>',
    'Co-Authored-By: OpenAI Codex <codex@openai.com>',
    'Co-Authored-By: ChatGPT <noreply@openai.com>',
    'Co-Authored-By: Gemini <gemini@example.com>',
    'Co-Authored-By: Cursor Agent <cursoragent@cursor.com>',
    'Co-Authored-By: someone <noreply@anthropic.com>',
    'Made-with: Cursor',
    'Generated by Claude Code',
    '🤖 Generated with [Claude Code](https://claude.com/claude-code)',
  ])('去掉末尾的 AI 署名：%s', (trailer) => {
    expect(stripAiTrailers(withTrailer(trailer))).toBe('fix: 修正\n\n正文\n')
  })

  it.each([
    'Co-Authored-By: Claude Dupont <claude.dupont@example.com>',
    'Co-Authored-By: Devin Chen <devin.chen@example.com>',
    'Co-authored-by: Aider Li <aider@example.com>',
    'Co-Authored-By: 刘伟 <cursor@example.com>',
    'Co-Authored-By: 张三 <zhangsan@example.com>',
    'Reviewed-by: 李四 <lisi@example.com>',
  ])('保留人类的署名：%s', (trailer) => {
    const message = withTrailer(trailer)
    expect(stripAiTrailers(message)).toBe(message)
  })

  it('同一段里既有人类又有 AI 署名时，只去掉 AI 的那一行', () => {
    const message = 'fix: 修正\n\nCo-Authored-By: 张三 <zhangsan@example.com>\nCo-Authored-By: Claude <noreply@anthropic.com>\n'
    expect(stripAiTrailers(message)).toBe('fix: 修正\n\nCo-Authored-By: 张三 <zhangsan@example.com>\n')
  })

  it('正文里举例写的署名行不动，只处理末尾的署名段', () => {
    const message = 'docs: 说明提交约定\n\n不要写这样的行：\nCo-Authored-By: Claude <noreply@anthropic.com>\n以免泄露工具信息。\n'
    expect(stripAiTrailers(message)).toBe(message)
  })

  it('保留 git 的注释行，并且只在末尾保留一个换行', () => {
    expect(stripAiTrailers('docs: 更新\n\n# 请输入提交说明\n\n\n')).toBe('docs: 更新\n\n# 请输入提交说明\n')
    expect(stripAiTrailers('docs: 更新\n\nCo-Authored-By: Claude <noreply@anthropic.com>\n# 注释\n')).toBe('docs: 更新\n\n# 注释\n')
  })

  it('git commit -v：只处理剪刀线之前的部分，剪刀线与 diff 原样保留', () => {
    const diff = '# ------------------------ >8 ------------------------\n# 不要修改或删除上面这一行。\ndiff --git a/x.ts b/x.ts\n+Co-Authored-By: Claude <noreply@anthropic.com>\n'
    const message = `fix: 修正\n\n正文\n\nCo-Authored-By: Claude Opus 5.5 (1M context) <noreply@anthropic.com>\n# 请为您的变更输入提交说明。\n${diff}`
    expect(stripAiTrailers(message)).toBe(`fix: 修正\n\n正文\n\n# 请为您的变更输入提交说明。\n${diff}`)
  })

  it.each([';', '//'])('非默认的注释符 %s：注释行与剪刀线都按它识别', (prefix) => {
    const scissors = `${prefix} ------------------------ >8 ------------------------`
    const message = `fix: 修正\n\nCo-Authored-By: Claude <noreply@anthropic.com>\n${prefix} 请输入提交说明\n${scissors}\ndiff --git a/x b/x\n`
    expect(stripAiTrailers(message, prefix)).toBe(`fix: 修正\n\n${prefix} 请输入提交说明\n${scissors}\ndiff --git a/x b/x\n`)
  })

  it('正文里提到 Claude 的普通句子不受影响', () => {
    const message = 'docs: 记录 Claude 相关的约定\n\n说明 Co-Authored-By 规则\n'
    expect(stripAiTrailers(message)).toBe(message)
  })
})
