// api 对外的程序接口（P2 设计 §3.2）：命令行与集成测试经这里建应用，走的是与进程入口相同的管线。
export { AuditModule, AuditService, RequestOrigin } from '../modules/audit/index.ts'
export type { AuditEvent, AuditOrigin } from '../modules/audit/index.ts'
export { ConfigError, loadConfig, loadConfigFromEnvironment } from '../modules/config/index.ts'
export type { AppConfig } from '../modules/config/index.ts'
export { DATABASE, DatabaseModule, MigrationError, MIGRATIONS_FOLDER, readExpectedMigrations, runMigrations, TransactionRunner } from '../modules/database/index.ts'
export type { Database, MigrationOutcome, SchemaStatus, Transaction } from '../modules/database/index.ts'
export { AppLogger } from '../modules/logging/index.ts'
// 集成测试的探针用：在一个事务里直接调用空间的服务（名称撞上唯一约束之后事务仍可继续，M2-P2 审查 A6）
export { SpacesModule, SpacesService } from '../modules/spaces/index.ts'
export type { AdminInitializationInput, InitializedAdmin } from '../modules/users/index.ts'
export { AppError } from '../shared/errors/app-error.ts'
export { Public } from '../shared/public.ts'
export { ApplicationRuntime } from './application-runtime.ts'
export { createApplication } from './create-application.ts'
export type { ApplicationOptions } from './create-application.ts'
export { initializeAdmin } from './initialize-admin.ts'
export type { InitializeAdminOptions } from './initialize-admin.ts'
export { issueResetLink } from './issue-reset-link.ts'
export type { IssueResetLinkOptions } from './issue-reset-link.ts'
export type { ShutdownResult } from './shutdown.ts'
