import type { LeaseVerdict } from '../edit-lease.ts'
import { afterEach, describe, expect, it, vi } from 'vitest'
import { gunzipBytes } from '../../../shared/outbox/draft-codec.ts'
import { CLIENT_INSTANCE_ID } from '../../../shared/outbox/draft-record.test-support.ts'
import { deferred } from '../../../shared/outbox/outbox-lock.test-support.ts'
import { settle } from '../fake-lease-clock.test-support.ts'
import { DRAFT_KEY, newKey, persistentHarness } from './persistent-working-draft.test-support.ts'
import { createPersistentWorkingDraft } from './persistent-working-draft.ts'

afterEach(() => vi.restoreAllMocks())
const capture = (snapshot: string) => ({ snapshot, editorSeq: 1, formulasPending: false, dedupe: true })

describe('持久草稿的暂停、换钥与恢复', () => {
  it('暂停发生在 unchanged 返回前，存储暂时读不了时仍用该捕获的临时正文保留真实内容序号', async () => {
    const h = await persistentHarness()
    const source = createPersistentWorkingDraft(h.options)
    await source.ready(source.capture(capture('相同正文')))
    const original = h.writer.write
    const reached = deferred<void>()
    const release = deferred<void>()
    vi.spyOn(h.writer, 'write').mockImplementationOnce(async (input) => {
      const result = await original(input)
      expect(result.kind).toBe('unchanged')
      reached.resolve()
      await release.promise
      return result
    })
    const ref = source.capture(capture('相同正文'))
    await reached.promise
    source.suspend()
    vi.spyOn(h.store.store, 'readDraft').mockResolvedValue({ kind: 'unavailable', reason: 'denied' })
    const resumed = source.resume()
    release.resolve()
    await resumed
    expect(await source.ready(ref)).toMatchObject({ contentSeq: 1 })
    expect(await source.readLatest()).toMatchObject({ ref, snapshot: '相同正文' })
    const upload = await source.prepare(ref)
    expect(upload).toMatchObject({ kind: 'prepared', contentSeq: 1 })
    if (upload.kind === 'prepared')
      expect(new TextDecoder().decode(await gunzipBytes(upload.gzip))).toBe('相同正文')
    source.dispose()
  })

  it('暂停发生在旧钥写入中，恢复等它交回正文才关宿主；新钥读不开旧记录时仍保留当前内容', async () => {
    const h = await persistentHarness()
    const held = h.store.holdNext('writeDraft')
    const source = createPersistentWorkingDraft(h.options)
    const ref = source.capture(capture('写入中的原文'))
    await held.reached
    source.suspend()
    h.changeKey(await newKey(2))
    const resumed = source.resume()
    await settle()
    const closedBeforeWriteFinished = h.hosts[0]!.host.broken()
    const hostsBeforeWriteFinished = h.host.mock.calls.length
    held.release()
    expect(await resumed).toMatchObject({ kind: 'memory', reason: 'existing-draft', existing: { kind: 'unreadable' } })
    expect(closedBeforeWriteFinished).toBe(false)
    expect(hostsBeforeWriteFinished).toBe(1)
    expect(await source.readLatest()).toMatchObject({ ref, snapshot: '写入中的原文' })
    source.dispose()
  })

  it('恢复核对仍在等待时再次暂停，迟到 current 不能启动新宿主或写回', async () => {
    const h = await persistentHarness()
    const source = createPersistentWorkingDraft(h.options)
    source.suspend()
    const ref = source.capture(capture('保留内容'))
    await source.ready(ref)
    const held = deferred<LeaseVerdict>()
    h.confirm.mockReturnValueOnce(held.promise)
    const resumed = source.resume()
    await settle()
    source.suspend()
    held.resolve({ kind: 'current' })
    expect(await resumed).toMatchObject({ kind: 'memory', reason: 'paused' })
    expect(h.host).toHaveBeenCalledTimes(1)
    expect(h.store.rawDraft(DRAFT_KEY)).toBeUndefined()
    expect(await source.readLatest()).toMatchObject({ ref, snapshot: '保留内容' })
    source.dispose()
  })

  it('相邻换钥只允许最后一代安装；已保留的旧读取不引入新正文所有者', async () => {
    const h = await persistentHarness()
    const source = createPersistentWorkingDraft(h.options)
    await source.ready(source.capture(capture('连续换钥')))
    await settle()
    const original = await h.writer.read(DRAFT_KEY)
    const held = deferred<typeof original>()
    vi.spyOn(h.session, 'read').mockReturnValueOnce(held.promise)
    const setKey = vi.spyOn(h.session, 'setKey')
    const second = await newKey(2)
    const third = await newKey(3)
    h.changeKey(second)
    const older = source.setKey(second)
    await settle()
    h.changeKey(third)
    const newer = source.setKey(third)
    held.resolve(original)
    expect(await older).toMatchObject({ kind: 'failed' })
    expect(await newer).toMatchObject({ kind: 'key-set' })
    expect(setKey).toHaveBeenCalledExactlyOnceWith(third)
    expect(h.store.rawDraft(DRAFT_KEY)).toMatchObject({ keyVersion: 3 })
    expect(await source.readLatest()).toMatchObject({ snapshot: '连续换钥' })
    source.dispose()
  })

  it('临时无钥的新捕获不销毁原宿主，下次取到钥在原宿主继续写', async () => {
    const h = await persistentHarness()
    const source = createPersistentWorkingDraft(h.options)
    await source.ready(source.capture(capture('第一份')))
    h.changeKey(undefined)
    await h.session.setKey(undefined)
    const missing = source.capture(capture('无钥时'))
    expect(await source.ready(missing)).toMatchObject({ local: { kind: 'memory', reason: 'no-key' } })
    expect(h.hosts[0]!.host.broken()).toBe(false)
    expect(h.confirm).not.toHaveBeenCalled()
    const next = await newKey(2)
    h.changeKey(next)
    const retried = source.capture(capture('新密钥内容'))
    expect(await source.ready(retried)).toMatchObject({ local: { kind: 'persisted' } })
    expect(h.host).toHaveBeenCalledTimes(1)
    expect(h.store.rawDraft(DRAFT_KEY)).toMatchObject({ keyVersion: 2, draftSeq: retried.draftSeq })
    source.dispose()
  })

  it('拒绝非法起点，即使登记有合法高水位也不能吞掉错误', async () => {
    const h = await persistentHarness()
    for (const initialDraftSeq of [-1, 0.5, Number.NaN, Number.POSITIVE_INFINITY])
      expect(() => createPersistentWorkingDraft({ ...h.options, initialDraftSeq })).toThrow(RangeError)
    h.session.dispose()
  })

  it('暂停同步封住新写入、标记与确认；旧内容和暂停中的新编辑均可读', async () => {
    const h = await persistentHarness()
    const source = createPersistentWorkingDraft(h.options)
    const ref = source.capture(capture('暂停前'))
    const upload = await source.prepare(ref)
    if (upload.kind !== 'prepared')
      throw new Error('需要已准备的上传')
    const write = vi.spyOn(h.session, 'write')
    const mark = vi.spyOn(h.session, 'markInFlight')
    const confirm = vi.spyOn(h.session, 'confirm')
    source.suspend()
    await settle()
    expect(await source.readLatest()).toMatchObject({ ref, snapshot: '暂停前' })
    expect(await source.markInFlight(upload, { requestId: 'paused', clientInstanceId: CLIENT_INSTANCE_ID, localSeq: upload.contentSeq, sentAt: 1_000 })).toMatchObject({ kind: 'memory', reason: 'paused' })
    expect(await source.confirm(upload, 8)).toMatchObject({ kind: 'memory', reason: 'paused' })
    const next = source.capture(capture('暂停后'))
    expect(await source.ready(next)).toMatchObject({ local: { kind: 'memory', reason: 'paused' } })
    expect(await source.readLatest()).toMatchObject({ ref: next, snapshot: '暂停后' })
    expect(write).not.toHaveBeenCalled()
    expect(mark).not.toHaveBeenCalled()
    expect(confirm).not.toHaveBeenCalled()
    source.dispose()
  })

  it('恢复先核对再登记，只重写核对期间最新的内存内容并吸收高水位', async () => {
    const h = await persistentHarness()
    h.store.failNext('writeDraft', { kind: 'quota' })
    const source = createPersistentWorkingDraft(h.options)
    await source.ready(source.capture(capture('旧内存')))
    source.suspend()
    const storedWriter = h.store.rawWriter(DRAFT_KEY) as object
    h.store.putRaw('writers', DRAFT_KEY, { ...storedWriter, lastDraftSeq: 90 })
    const held = deferred<LeaseVerdict>()
    h.confirm.mockReturnValueOnce(held.promise)
    const resumed = source.resume()
    await settle()
    const newer = source.capture(capture('核对期间的新编辑'))
    await source.ready(newer)
    expect(h.host).toHaveBeenCalledTimes(1)
    held.resolve({ kind: 'current' })
    expect(await resumed).toMatchObject({ kind: 'ready' })
    const current = source.view()
    expect(current).toMatchObject({ local: { kind: 'persisted' }, ref: { draftSeq: 91 } })
    expect(await source.readLatest()).toMatchObject({ snapshot: '核对期间的新编辑' })
    expect(h.store.rawDraft(DRAFT_KEY)).toMatchObject({ draftSeq: 91 })
    source.dispose()
  })

  it('恢复遇到旧记录保留原记录，当前内容已留在来源，不能自动接手覆盖', async () => {
    const h = await persistentHarness()
    const source = createPersistentWorkingDraft(h.options)
    const ref = source.capture(capture('暂停草稿'))
    await source.ready(ref)
    const before = h.store.rawDraft(DRAFT_KEY)
    source.suspend()
    expect(await source.resume()).toMatchObject({ kind: 'memory', reason: 'existing-draft' })
    expect(h.store.rawDraft(DRAFT_KEY)).toEqual(before)
    expect(await source.readLatest()).toMatchObject({ ref, snapshot: '暂停草稿' })
    source.dispose()
  })

  it('换钥重封失败时用当前内容强制重写，固定旧上传的字节和基准不变', async () => {
    const h = await persistentHarness()
    const source = createPersistentWorkingDraft(h.options)
    const ref = source.capture(capture('同一内容'))
    const upload = await source.prepare(ref)
    if (upload.kind !== 'prepared')
      throw new Error('需要上传')
    const bytes = upload.gzip.slice()
    h.store.failNext('replaceDraft', { kind: 'quota' })
    const next = await newKey(2)
    h.changeKey(next)
    expect(await source.setKey(next)).toEqual({ kind: 'key-set', notResealed: [DRAFT_KEY] })
    expect(source.view()).toMatchObject({ ref: { draftSeq: 2 }, local: { kind: 'persisted' } })
    expect(h.store.rawDraft(DRAFT_KEY)).toMatchObject({ keyVersion: 2, draftSeq: 2 })
    expect(upload.gzip).toEqual(bytes)
    expect(upload.baseRevision).toBe(7)
    source.dispose()
  })

  it('换钥读回期间的新编辑胜出，晚到旧正文不能覆盖它', async () => {
    const h = await persistentHarness()
    const source = createPersistentWorkingDraft(h.options)
    await source.ready(source.capture(capture('旧正文')))
    await settle()
    const original = await h.writer.read(DRAFT_KEY)
    const held = deferred<typeof original>()
    vi.spyOn(h.session, 'read').mockReturnValueOnce(held.promise)
    const next = await newKey(2)
    h.changeKey(next)
    const changing = source.setKey(next)
    await settle()
    source.capture(capture('换钥期间的新正文'))
    held.resolve(original)
    expect(await changing).toMatchObject({ kind: 'key-set' })
    expect(await source.readLatest()).toMatchObject({ snapshot: '换钥期间的新正文' })
    expect(h.store.rawDraft(DRAFT_KEY)).toMatchObject({ keyVersion: 2, draftSeq: 3 })
    source.dispose()
  })

  it.each(['suspend', 'dispose'] as const)('换钥读回期间 %s，晚到结果不安装新钥或重写', async (stop) => {
    const h = await persistentHarness()
    const source = createPersistentWorkingDraft(h.options)
    await source.ready(source.capture(capture('原文')))
    await settle()
    const original = await h.writer.read(DRAFT_KEY)
    const held = deferred<typeof original>()
    vi.spyOn(h.session, 'read').mockReturnValueOnce(held.promise)
    const setKey = vi.spyOn(h.session, 'setKey')
    const next = await newKey(2)
    h.changeKey(next)
    const changing = source.setKey(next)
    await settle()
    source[stop]()
    held.resolve(original)
    expect(await changing).toMatchObject({ kind: 'failed' })
    expect(setKey).not.toHaveBeenCalled()
    expect(h.store.rawDraft(DRAFT_KEY)).toMatchObject({ keyVersion: 1, draftSeq: 1 })
    source.dispose()
  })
})
