export type { MemberRoleChange, SpaceChange, SpaceFacts, SpaceMemberRecord, SpaceRecord, SpaceSummary, TeamSpaceOverview } from './space.ts'
export { SpacesModule } from './spaces.module.ts'
export { SpacesService } from './spaces.service.ts'
export type { CreateOptions as CreateSpaceOptions, NewTeamSpace } from './spaces.service.ts'
export type { QueryOptions as SpaceQueryOptions } from './spaces.service.ts'
